{
	{
		Groups = false,
		LootTableIds = {
			"LargeContainer",
		},
		handle = 197083136,
		map = "mvrwGoj",
		name = 'InventoryItemSpawn#136 "CONTAINER"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"IntelSecretStash",
		},
		handle = 569008128,
		map = "mvrwGoj",
		name = 'IntelInventoryItemSpawn#128 "SECRET STASH"',
		path = "IntelInventoryItemSpawn ",
		type = "IntelInventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"IntelSecretStash",
		},
		handle = 767811584,
		map = "mvrwGoj",
		name = 'IntelInventoryItemSpawn#584 "SECRET STASH"',
		path = "IntelInventoryItemSpawn ",
		type = "IntelInventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"IntelSecretStash",
		},
		handle = 861233152,
		map = "mvrwGoj",
		name = 'IntelInventoryItemSpawn#152 "SECRET STASH"',
		path = "IntelInventoryItemSpawn ",
		type = "IntelInventoryItemSpawn",
	},
	{
		Groups = {
			"SlaversGroup",
		},
		handle = 1003209574,
		items = {},
		map = "mvrwGoj",
		name = "UnitMarker#574 (SlaversGroup)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"SlaversGroup",
		},
		handle = 1004059832,
		items = {},
		map = "mvrwGoj",
		name = "UnitMarker#832 (SlaversGroup)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"SlaversGroup",
		},
		handle = 1016061603,
		items = {},
		map = "mvrwGoj",
		name = "UnitMarker#603 (SlaversGroup)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1033891295,
		items = {},
		map = "mvrwGoj",
		name = "UnitMarker#295",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"SlaversGroup",
		},
		handle = 1034441477,
		items = {},
		map = "mvrwGoj",
		name = "UnitMarker#477 (SlaversGroup)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"SlaversGroup",
		},
		handle = 1042192422,
		items = {},
		map = "mvrwGoj",
		name = "UnitMarker#422 (SlaversGroup)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"SlaversGroup",
		},
		handle = 1084544729,
		items = {},
		map = "mvrwGoj",
		name = "UnitMarker#729 (SlaversGroup)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterGroups = {
			"Banters_Civilians",
		},
		Groups = {
			"AL_Patrons",
		},
		handle = 1101110072,
		map = "mvrwGoj",
		name = "AmbientZone#072 (AL_Patrons)",
		path = "AmbientZone ",
		type = "AmbientZone",
	},
	{
		Groups = {
			"SlaversGroup",
		},
		handle = 1159447279,
		items = {},
		map = "mvrwGoj",
		name = "UnitMarker#279 (SlaversGroup)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1162064201,
		items = {},
		map = "mvrwGoj",
		name = "UnitMarker#201",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterGroups = {
			"Banters_Civilians",
		},
		Groups = {
			"AL_Bar",
		},
		handle = 1164841012,
		map = "mvrwGoj",
		name = "AmbientZone#012 (AL_Bar)",
		path = "AmbientZone ",
		type = "AmbientZone",
	},
	{
		Groups = {
			"SlaversGroup",
		},
		handle = 1175248465,
		items = {},
		map = "mvrwGoj",
		name = "UnitMarker#465 (SlaversGroup)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"SlaversGroup",
		},
		handle = 1261102996,
		items = {},
		map = "mvrwGoj",
		name = "UnitMarker#996 (SlaversGroup)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"SlaversGroup",
		},
		handle = 1264209815,
		items = {},
		map = "mvrwGoj",
		name = "UnitMarker#815 (SlaversGroup)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"SlaversGroup",
		},
		handle = 1298058050,
		items = {},
		map = "mvrwGoj",
		name = "UnitMarker#050 (SlaversGroup)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1304283242,
		items = {},
		map = "mvrwGoj",
		name = "UnitMarker#242",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterGroups = {
			"Banters_Civilians",
		},
		Groups = {
			"AL_Bar_Waitress",
		},
		handle = 1332475823,
		map = "mvrwGoj",
		name = "AmbientZone#823 (AL_Bar_Waitress)",
		path = "AmbientZone ",
		type = "AmbientZone",
	},
	{
		Groups = {
			"SlaversGroup",
		},
		handle = 1351970549,
		items = {},
		map = "mvrwGoj",
		name = "UnitMarker#549 (SlaversGroup)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"SlaversGroup",
		},
		handle = 1357735924,
		items = {},
		map = "mvrwGoj",
		name = "UnitMarker#924 (SlaversGroup)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1364834276,
		items = {},
		map = "mvrwGoj",
		name = "UnitMarker#276",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"SlaversGroup",
		},
		handle = 1405600106,
		items = {},
		map = "mvrwGoj",
		name = "UnitMarker#106 (SlaversGroup)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"SlaversGroup",
		},
		handle = 1470458099,
		items = {},
		map = "mvrwGoj",
		name = "UnitMarker#099 (SlaversGroup)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"SlaversGroup",
		},
		handle = 1599035231,
		items = {},
		map = "mvrwGoj",
		name = "UnitMarker#231 (SlaversGroup)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"SlaversGroup",
		},
		handle = 1628736611,
		items = {},
		map = "mvrwGoj",
		name = "UnitMarker#611 (SlaversGroup)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"SlaversGroup",
		},
		handle = 1635414691,
		items = {},
		map = "mvrwGoj",
		name = "UnitMarker#691 (SlaversGroup)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"SlaversGroup",
		},
		handle = 1696303746,
		items = {},
		map = "mvrwGoj",
		name = "UnitMarker#746 (SlaversGroup)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"SlaversGroup",
		},
		handle = 1798203666,
		items = {},
		map = "mvrwGoj",
		name = "UnitMarker#666 (SlaversGroup)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1801984636,
		items = {},
		map = "mvrwGoj",
		name = "UnitMarker#636",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"SlaversGroup",
		},
		handle = 1815289788,
		items = {},
		map = "mvrwGoj",
		name = "UnitMarker#788 (SlaversGroup)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"SlaversGroup",
		},
		handle = 1828508238,
		items = {},
		map = "mvrwGoj",
		name = "UnitMarker#238 (SlaversGroup)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
}