{
	{
		Groups = false,
		LootTableIds = {
			"LargeContainer_Exceptional",
		},
		handle = 194109440,
		map = "Nzfk5d6",
		name = 'InventoryItemSpawn#440 "Bag"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"SmallContainer_Exceptional",
		},
		handle = 520167424,
		map = "Nzfk5d6",
		name = 'InventoryItemSpawn#424 "Bag"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"Fracture_Rigged_Loot",
		},
		handle = 847011840,
		map = "Nzfk5d6",
		name = 'InventoryItemSpawn#840 "Bag"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		handle = 1013178725,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#725",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave3",
		},
		handle = 1035441722,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#722 (Waves_All, Wave3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1035547356,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#356",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1055526604,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#604",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1065236300,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#300",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave3",
		},
		handle = 1085019993,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#993 (Waves_All, Wave3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1085389402,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#402",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1091280385,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#385",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave1",
		},
		handle = 1092281844,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#844 (Waves_All, Wave1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1095898258,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#258",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave3",
		},
		handle = 1101917395,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#395 (Waves_All, Wave3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1121296839,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#839",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave2",
		},
		handle = 1162452384,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#384 (Waves_All, Wave2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1163092363,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#363",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave3",
		},
		handle = 1170774847,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#847 (Waves_All, Wave3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Patroller",
		},
		handle = 1206164863,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#863 (Patroller)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1229605249,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#249",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1254498820,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#820",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave1",
		},
		handle = 1272754717,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#717 (Waves_All, Wave1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave1",
		},
		handle = 1284531128,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#128 (Waves_All, Wave1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1327391894,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#894",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave2",
		},
		handle = 1331717561,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#561 (Waves_All, Wave2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1367347268,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#268",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1373072578,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#578",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave1",
		},
		handle = 1406478533,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#533 (Waves_All, Wave1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave3",
		},
		handle = 1450498930,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#930 (Waves_All, Wave3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1456844784,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#784",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1467070192,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#192",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1474882443,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#443",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave1",
		},
		handle = 1484309015,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#015 (Waves_All, Wave1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1488937604,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#604",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave3",
		},
		handle = 1506956002,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#002 (Waves_All, Wave3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave1",
		},
		handle = 1540110226,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#226 (Waves_All, Wave1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1578075641,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#641",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1584125430,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#430",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave2",
		},
		handle = 1608733245,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#245 (Waves_All, Wave2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave2",
		},
		handle = 1622281971,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#971 (Waves_All, Wave2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1638865047,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#047",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave1",
		},
		handle = 1641480348,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#348 (Waves_All, Wave1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave3",
		},
		handle = 1642332101,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#101 (Waves_All, Wave3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1651727739,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#739",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave2",
		},
		handle = 1651856943,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#943 (Waves_All, Wave2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1652529751,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#751",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Patroller",
		},
		handle = 1706653237,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#237 (Patroller)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave1",
		},
		handle = 1767474411,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#411 (Waves_All, Wave1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1769408294,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#294",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave2",
		},
		handle = 1805705841,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#841 (Waves_All, Wave2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1852908212,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#212",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave3",
		},
		handle = 1859974834,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#834 (Waves_All, Wave3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1897204596,
		items = {},
		map = "Nzfk5d6",
		name = "UnitMarker#596",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
}