{
	{
		Groups = false,
		LootTableIds = {
			"SmallContainer",
		},
		handle = 46563328,
		map = "LaRmEyu",
		name = 'InventoryItemSpawn#328 "PILE"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = {
			"SkillChest_Loot",
		},
		LootTableIds = {
			"TwinManorsClinicCabinetLoot",
		},
		handle = 204980224,
		items = {
			{
				editor_view_abridged = "if Given",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestIsVariableBool",
				var = set( "Given" ),
			},
			{
				editor_view_abridged = "if ClueDoctorPoison",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestIsVariableBool",
				var = set( "ClueDoctorPoison" ),
			},
		},
		map = "LaRmEyu",
		name = 'InventoryItemSpawn#224 "SECRET STASH" (SkillChest_Loot)',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"LargeContainer",
		},
		handle = 306126848,
		map = "LaRmEyu",
		name = 'InventoryItemSpawn#848 "CONTAINER"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"SmallContainer",
		},
		handle = 367484928,
		map = "LaRmEyu",
		name = 'InventoryItemSpawn#928 "CONTAINER"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"SmallContainer",
		},
		handle = 516644864,
		map = "LaRmEyu",
		name = 'InventoryItemSpawn#864 "CONTAINER"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = {
			"DualSkillChest_Loot",
		},
		LootTableIds = {
			"TwinManorsClinicAutopsy",
		},
		handle = 750895104,
		items = {
			{
				editor_view_abridged = "if ClueDoctorAutopsies",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestIsVariableBool",
				var = set( "ClueDoctorAutopsies" ),
			},
		},
		map = "LaRmEyu",
		name = 'InventoryItemSpawn#104 "CONTAINER" (DualSkillChest_Loot)',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"TwinManors_VanTasselCabinet",
				},
				banterSequentialWaitFor = "BanterLineStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = {
			"LockedClue",
		},
		LootTableIds = {
			"TwinManorsVanTasselCabinet",
		},
		handle = 855695360,
		items = {
			{
				editor_view_abridged = "ClueManorAmmo = true",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestSetVariableBool",
				var = "ClueManorAmmo",
			},
			{
				editor_view_abridged = "Quest TwinManors:Clues =  100% from (Clues + 1)",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestSetVariableNum",
				var = "Clues",
			},
			{
				editor_view_abridged = "if Given",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestIsVariableBool",
				var = set( "Given" ),
			},
			{
				editor_view_abridged = "if ClueManorAmmo",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestIsVariableBool",
				var = set( "ClueManorAmmo" ),
			},
			{
				editor_view_abridged = "Play banter(s): TwinManors_VanTasselCabinet",
				filter_type = "banter",
				reference_id = "TwinManors_VanTasselCabinet",
				type = "PlayBanterEffect",
			},
		},
		map = "LaRmEyu",
		name = 'InventoryItemSpawn#360 "CONTAINER" (LockedClue)',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"LargeContainer",
		},
		handle = 882393088,
		map = "LaRmEyu",
		name = 'InventoryItemSpawn#088 "CONTAINER"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"SmallContainer",
		},
		handle = 888512512,
		map = "LaRmEyu",
		name = 'InventoryItemSpawn#512 "CONTAINER"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"LargeContainer",
		},
		handle = 895442944,
		map = "LaRmEyu",
		name = 'InventoryItemSpawn#944 "CONTAINER"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"TwinManors_LeDomasCabinet",
				},
				banterSequentialWaitFor = "BanterLineStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = {
			"LockedClue2",
		},
		LootTableIds = {
			"TwinManorsLeDomasCabinet",
		},
		handle = 961716224,
		items = {
			{
				editor_view_abridged = "ClueManorPoison = true",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestSetVariableBool",
				var = "ClueManorPoison",
			},
			{
				editor_view_abridged = "Quest TwinManors:Clues =  100% from (Clues + 1)",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestSetVariableNum",
				var = "Clues",
			},
			{
				editor_view_abridged = "if Given",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestIsVariableBool",
				var = set( "Given" ),
			},
			{
				editor_view_abridged = "if ClueManorPoison",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestIsVariableBool",
				var = set( "ClueManorPoison" ),
			},
			{
				editor_view_abridged = "Play banter(s): TwinManors_LeDomasCabinet",
				filter_type = "banter",
				reference_id = "TwinManors_LeDomasCabinet",
				type = "PlayBanterEffect",
			},
		},
		map = "LaRmEyu",
		name = 'InventoryItemSpawn#224 "CONTAINER" (LockedClue2)',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = {
			"SkillChest_Loot",
		},
		LootTableIds = {
			"TwinManorsClinicDeskLoot",
		},
		handle = 998719488,
		items = {
			{
				editor_view_abridged = "if Given",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestIsVariableBool",
				var = set( "Given" ),
			},
			{
				editor_view_abridged = "if ClueDoctorAmmo",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestIsVariableBool",
				var = set( "ClueDoctorAmmo" ),
			},
		},
		map = "LaRmEyu",
		name = 'InventoryItemSpawn#488 "SECRET STASH" (SkillChest_Loot)',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		BanterGroups = {
			"Banters_Local_TwinManors",
			"Banters_Civilians",
		},
		Groups = {
			"AL_VanTassel",
			"FamiliesCombat",
			"VanTassel",
			"VanTasselCombat",
			"CivilianFemale_2",
		},
		handle = 1003626310,
		items = {},
		map = "LaRmEyu",
		name = "UnitMarker#310 (AL_VanTassel, FamiliesCombat, VanTassel, VanTasselCombat, CivilianFemale_2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"TwinManors_ClinicCabinet",
				},
				banterSequentialWaitFor = "BanterLineStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = {
			"SkillChest",
		},
		handle = 1043805036,
		items = {
			{
				editor_view_abridged = "if Given",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestIsVariableBool",
				var = set( "Given" ),
			},
			{
				editor_view_abridged = "Quest TwinManors:Clues =  100% from (Clues + 1)",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestSetVariableNum",
				var = "Clues",
			},
			{
				editor_view_abridged = "ClueDoctorPoison = true",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestSetVariableBool",
				var = "ClueDoctorPoison",
			},
			{
				editor_view_abridged = "Play banter(s): TwinManors_ClinicCabinet",
				filter_type = "banter",
				reference_id = "TwinManors_ClinicCabinet",
				type = "PlayBanterEffect",
			},
		},
		map = "LaRmEyu",
		name = 'CustomInteractable#036 "Examine" (SkillChest)',
		path = "CustomInteractable ",
		type = "CustomInteractable",
	},
	{
		BanterGroups = {
			"Banters_Local_TwinManors",
			"Banters_Civilians",
		},
		Groups = {
			"AL_VanTassel",
			"FamiliesCombat",
			"VanTassel",
			"VanTasselCombat",
			"CivilianMale_2",
			"VanTasselActorMale",
		},
		handle = 1096726269,
		items = {},
		map = "LaRmEyu",
		name = "UnitMarker#269 (AL_VanTassel, FamiliesCombat, VanTassel, VanTasselCombat, CivilianMale_2, VanTasselActorMale)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterGroups = {
			"Banters_Local_TwinManors",
			"Banters_Civilians",
		},
		Groups = {
			"FamiliesCombat",
			"AL_LeDonnas",
			"LeDonnas",
			"LeDomasCombat",
			"CivilianMale_1",
		},
		handle = 1120924365,
		items = {},
		map = "LaRmEyu",
		name = "UnitMarker#365 (FamiliesCombat, AL_LeDonnas, LeDonnas, LeDomasCombat, CivilianMale_1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterGroups = {
			"SharedOverheard_Civilians",
		},
		Groups = {
			"Overheard_Civilian",
		},
		handle = 1126860660,
		items = {
			{
				editor_view_abridged = "if not FamilyGathering and Given",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestIsVariableBool",
				var = set({
	FamilyGathering = false,
	Given = true,
}),
			},
		},
		map = "LaRmEyu",
		name = "Position#660 (Overheard_Civilian)",
		path = "Position ",
		type = "Position",
	},
	{
		BanterGroups = {
			"SharedOverheard_Civilians",
		},
		Groups = {
			"Overheard_Civilian",
		},
		handle = 1130246988,
		items = {
			{
				editor_view_abridged = "if not FamilyGathering and Given",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestIsVariableBool",
				var = set({
	FamilyGathering = false,
	Given = true,
}),
			},
		},
		map = "LaRmEyu",
		name = "Position#988 (Overheard_Civilian)",
		path = "Position ",
		type = "Position",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"TwinManors_ClinicArchiveExamine",
				},
				banterSequentialWaitFor = "BanterLineStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = {
			"ExamineMarker",
		},
		handle = 1156014968,
		items = {
			{
				editor_view_abridged = "if Given",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestIsVariableBool",
				var = set( "Given" ),
			},
			{
				editor_view_abridged = "Play banter(s): TwinManors_ClinicArchiveExamine",
				filter_type = "banter",
				reference_id = "TwinManors_ClinicArchiveExamine",
				type = "PlayBanterEffect",
			},
		},
		map = "LaRmEyu",
		name = 'CustomInteractable#968 "Examine" (ExamineMarker)',
		path = "CustomInteractable ",
		type = "CustomInteractable",
	},
	{
		BanterGroups = {
			"Banters_Local_TwinManors",
			"Banters_Civilians",
		},
		Groups = {
			"FamiliesCombat",
			"AL_LeDonnas",
			"LeDonnas",
			"LeDomasCombat",
			"CivilianFemale_1",
			"LeDomasActorFemale",
		},
		handle = 1221207720,
		items = {},
		map = "LaRmEyu",
		name = "UnitMarker#720 (FamiliesCombat, AL_LeDonnas, LeDonnas, LeDomasCombat, CivilianFemale_1, LeDomasActorFemale)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterGroups = {
			"SharedOverheard_Civilians",
		},
		Groups = {
			"Overheard_Civilian",
		},
		handle = 1225743535,
		items = {
			{
				editor_view_abridged = "if not FamilyGathering and Given",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestIsVariableBool",
				var = set({
	FamilyGathering = false,
	Given = true,
}),
			},
		},
		map = "LaRmEyu",
		name = "Position#535 (Overheard_Civilian)",
		path = "Position ",
		type = "Position",
	},
	{
		BanterGroups = {
			"Banters_Local_TwinManors",
			"Banters_Civilians",
		},
		Groups = {
			"AL_VanTassel",
			"FamiliesCombat",
			"VanTassel",
			"VanTasselCombat",
			"CivilianFemale_2",
		},
		handle = 1275260505,
		items = {},
		map = "LaRmEyu",
		name = "UnitMarker#505 (AL_VanTassel, FamiliesCombat, VanTassel, VanTasselCombat, CivilianFemale_2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterGroups = {
			"Banters_Local_TwinManors",
			"Banters_Civilians",
		},
		Groups = {
			"AL_VanTassel",
			"FamiliesCombat",
			"VanTassel",
			"VanTasselCombat",
			"CivilianMale_2",
		},
		handle = 1331589058,
		items = {},
		map = "LaRmEyu",
		name = "UnitMarker#058 (AL_VanTassel, FamiliesCombat, VanTassel, VanTasselCombat, CivilianMale_2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Hyenas",
		},
		handle = 1380700854,
		items = {},
		map = "LaRmEyu",
		name = "UnitMarker#854 (Hyenas)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterGroups = {
			"Banters_Local_TwinManors",
			"Banters_Civilians",
		},
		Groups = {
			"FamiliesCombat",
			"AL_LeDonnas",
			"LeDonnas",
			"LeDomasCombat",
			"CivilianMale_1",
		},
		handle = 1394299283,
		items = {},
		map = "LaRmEyu",
		name = "UnitMarker#283 (FamiliesCombat, AL_LeDonnas, LeDonnas, LeDomasCombat, CivilianMale_1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterGroups = {
			"Banters_Local_TwinManors",
			"Banters_Civilians",
		},
		Groups = {
			"AL_VanTassel",
			"FamiliesCombat",
			"VanTassel",
			"VanTasselCombat",
			"CivilianMale_2",
		},
		handle = 1422700284,
		items = {},
		map = "LaRmEyu",
		name = "UnitMarker#284 (AL_VanTassel, FamiliesCombat, VanTassel, VanTasselCombat, CivilianMale_2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterGroups = {
			"Banters_Local_TwinManors",
			"Banters_Civilians",
		},
		Groups = {
			"FamiliesCombat",
			"AL_LeDonnas",
			"LeDonnas",
			"LeDomasCombat",
			"CivilianMale_1",
		},
		handle = 1459624835,
		items = {},
		map = "LaRmEyu",
		name = "UnitMarker#835 (FamiliesCombat, AL_LeDonnas, LeDonnas, LeDomasCombat, CivilianMale_1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Hyenas",
		},
		handle = 1464162731,
		items = {},
		map = "LaRmEyu",
		name = "UnitMarker#731 (Hyenas)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"TwinManors_StageGun",
				},
				banterSequentialWaitFor = "BanterLineStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = {
			"ExamineMarker",
		},
		handle = 1486662436,
		items = {
			{
				editor_view_abridged = "if Given",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestIsVariableBool",
				var = set( "Given" ),
			},
			{
				editor_view_abridged = "Quest TwinManors:Clues =  100% from (Clues + 1)",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestSetVariableNum",
				var = "Clues",
			},
			{
				editor_view_abridged = "ClueStageAmmo = true",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestSetVariableBool",
				var = "ClueStageAmmo",
			},
			{
				editor_view_abridged = "Play banter(s): TwinManors_StageGun",
				filter_type = "banter",
				reference_id = "TwinManors_StageGun",
				type = "PlayBanterEffect",
			},
		},
		map = "LaRmEyu",
		name = 'CustomInteractable#436 "Examine" (ExamineMarker)',
		path = "CustomInteractable ",
		type = "CustomInteractable",
	},
	{
		BanterGroups = {
			"Banters_Local_TwinManors",
			"Banters_Civilians",
		},
		Groups = {
			"AL_VanTassel",
			"FamiliesCombat",
			"VanTassel",
			"VanTasselCombat",
			"CivilianMale_2",
		},
		handle = 1516073427,
		items = {},
		map = "LaRmEyu",
		name = "UnitMarker#427 (AL_VanTassel, FamiliesCombat, VanTassel, VanTasselCombat, CivilianMale_2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterGroups = {
			"Banters_Local_TwinManors",
			"Banters_Civilians",
		},
		Groups = {
			"VanTassel",
			"Families",
			"AL_VanTassel",
		},
		handle = 1516992314,
		map = "LaRmEyu",
		name = "AmbientZone#314 (VanTassel, Families, AL_VanTassel)",
		path = "AmbientZone ",
		type = "AmbientZone",
	},
	{
		BanterGroups = {
			"Banters_Local_TwinManors",
		},
		Groups = {
			"FamilyGathering",
		},
		handle = 1560832949,
		items = {},
		map = "LaRmEyu",
		name = "UnitMarker#949 (FamilyGathering)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('BanterHasPlayed', {
				Banters = {
					"TwinManors_ClinicArchiveExamine",
				},
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"TwinManors_ClinicArchive_success",
				},
				banterSequentialWaitFor = "BanterLineStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"TwinManors_ClinicArchive_failure",
				},
				banterSequentialWaitFor = "BanterLineStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = {
			"DualSkillChest",
		},
		handle = 1569932087,
		items = {
			{
				editor_view_abridged = "ClueDoctorAutopsies = true",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestSetVariableBool",
				var = "ClueDoctorAutopsies",
			},
			{
				editor_view_abridged = "Quest TwinManors:Clues =  100% from (Clues + 1)",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestSetVariableNum",
				var = "Clues",
			},
			{
				editor_view_abridged = "If any of banter(s) played: TwinManors_ClinicArchiveExamine",
				filter_type = "banter",
				reference_id = "TwinManors_ClinicArchiveExamine",
				type = "BanterHasPlayed",
			},
			{
				editor_view_abridged = "Play banter(s): TwinManors_ClinicArchive_success",
				filter_type = "banter",
				reference_id = "TwinManors_ClinicArchive_success",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): TwinManors_ClinicArchive_failure",
				filter_type = "banter",
				reference_id = "TwinManors_ClinicArchive_failure",
				type = "PlayBanterEffect",
			},
		},
		map = "LaRmEyu",
		name = 'CustomInteractable#087 "Examine" (DualSkillChest)',
		path = "CustomInteractable ",
		type = "CustomInteractable",
	},
	{
		BanterGroups = {
			"Banters_Local_TwinManors",
			"Banters_Civilians",
		},
		Groups = {
			"FamiliesCombat",
			"AL_LeDonnas",
			"LeDonnas",
			"LeDomasCombat",
			"CivilianMale_1",
			"LeDomasActorMale",
		},
		handle = 1572012052,
		items = {},
		map = "LaRmEyu",
		name = "UnitMarker#052 (FamiliesCombat, AL_LeDonnas, LeDonnas, LeDomasCombat, CivilianMale_1, LeDomasActorMale)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterGroups = {
			"Banters_Local_TwinManors",
			"Banters_Civilians",
		},
		Groups = {
			"AL_VanTassel",
			"FamiliesCombat",
			"VanTassel",
			"VanTasselCombat",
			"CivilianFemale_2",
			"VanTasselActorFemale",
		},
		handle = 1574044766,
		items = {},
		map = "LaRmEyu",
		name = "UnitMarker#766 (AL_VanTassel, FamiliesCombat, VanTassel, VanTasselCombat, CivilianFemale_2, VanTasselActorFemale)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"TwinManors_ClinicDesk",
				},
				banterSequentialWaitFor = "BanterLineStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = {
			"SkillChest",
		},
		handle = 1576204622,
		items = {
			{
				editor_view_abridged = "if Given",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestIsVariableBool",
				var = set( "Given" ),
			},
			{
				editor_view_abridged = "Quest TwinManors:Clues =  100% from (Clues + 1)",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestSetVariableNum",
				var = "Clues",
			},
			{
				editor_view_abridged = "ClueDoctorAmmo = true",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestSetVariableBool",
				var = "ClueDoctorAmmo",
			},
			{
				editor_view_abridged = "Play banter(s): TwinManors_ClinicDesk",
				filter_type = "banter",
				reference_id = "TwinManors_ClinicDesk",
				type = "PlayBanterEffect",
			},
		},
		map = "LaRmEyu",
		name = 'CustomInteractable#622 "Examine" (SkillChest)',
		path = "CustomInteractable ",
		type = "CustomInteractable",
	},
	{
		BanterGroups = {
			"Banters_Local_TwinManors",
			"Banters_Civilians",
		},
		Groups = {
			"AL_VanTassel",
			"FamiliesCombat",
			"VanTassel",
			"VanTasselCombat",
			"CivilianMale_2",
		},
		handle = 1600891973,
		items = {},
		map = "LaRmEyu",
		name = "UnitMarker#973 (AL_VanTassel, FamiliesCombat, VanTassel, VanTasselCombat, CivilianMale_2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterGroups = {
			"Banters_Local_TwinManors",
			"Banters_Civilians",
		},
		Groups = {
			"FamiliesCombat",
			"AL_LeDonnas",
			"LeDonnas",
			"LeDomasCombat",
			"CivilianFemale_1",
		},
		handle = 1603823054,
		items = {},
		map = "LaRmEyu",
		name = "UnitMarker#054 (FamiliesCombat, AL_LeDonnas, LeDonnas, LeDomasCombat, CivilianFemale_1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterGroups = {
			"Banters_Local_TwinManors",
			"Banters_Civilians",
		},
		Groups = {
			"FamiliesCombat",
			"AL_LeDonnas",
			"LeDonnas",
			"LeDomasCombat",
			"CivilianMale_1",
		},
		handle = 1617435695,
		items = {},
		map = "LaRmEyu",
		name = "UnitMarker#695 (FamiliesCombat, AL_LeDonnas, LeDonnas, LeDomasCombat, CivilianMale_1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterGroups = {
			"Banters_Local_TwinManors",
			"Banters_Civilians",
		},
		Groups = {
			"LeDonnas",
			"Families",
			"AL_LeDonnas",
		},
		handle = 1632876723,
		map = "LaRmEyu",
		name = "AmbientZone#723 (LeDonnas, Families, AL_LeDonnas)",
		path = "AmbientZone ",
		type = "AmbientZone",
	},
	{
		BanterGroups = {
			"Banters_Local_TwinManors",
			"Banters_Civilians",
		},
		Groups = {
			"FamiliesCombat",
			"AL_LeDonnas",
			"LeDonnas",
			"LeDomasCombat",
			"CivilianMale_1",
		},
		handle = 1762171756,
		items = {},
		map = "LaRmEyu",
		name = "UnitMarker#756 (FamiliesCombat, AL_LeDonnas, LeDonnas, LeDomasCombat, CivilianMale_1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterGroups = {
			"Banters_Local_TwinManors",
			"Banters_Civilians",
		},
		Groups = {
			"AL_VanTassel",
			"FamiliesCombat",
			"VanTassel",
			"VanTasselCombat",
			"CivilianMale_2",
		},
		handle = 1762357693,
		items = {},
		map = "LaRmEyu",
		name = "UnitMarker#693 (AL_VanTassel, FamiliesCombat, VanTassel, VanTasselCombat, CivilianMale_2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterGroups = {
			"Banters_Local_TwinManors",
			"Banters_Civilians",
		},
		Groups = {
			"FamiliesCombat",
			"AL_LeDonnas",
			"LeDonnas",
			"LeDomasCombat",
			"CivilianMale_1",
		},
		handle = 1804960810,
		items = {},
		map = "LaRmEyu",
		name = "UnitMarker#810 (FamiliesCombat, AL_LeDonnas, LeDonnas, LeDomasCombat, CivilianMale_1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterGroups = {
			"Banters_Local_TwinManors",
		},
		Groups = {
			"FamilyGathering",
		},
		handle = 1838123631,
		items = {},
		map = "LaRmEyu",
		name = "UnitMarker#631 (FamilyGathering)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"TwinManors_StagePotion_success",
				},
				banterSequentialWaitFor = "BanterLineStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"TwinManors_StagePotion_failure",
				},
				banterSequentialWaitFor = "BanterLineStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = {
			"SkillCheck",
		},
		handle = 1864756961,
		items = {
			{
				editor_view_abridged = "if Given",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestIsVariableBool",
				var = set( "Given" ),
			},
			{
				editor_view_abridged = "Quest TwinManors:Clues =  100% from (Clues + 1)",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestSetVariableNum",
				var = "Clues",
			},
			{
				editor_view_abridged = "ClueStagePoisonStrychnine = true",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestSetVariableBool",
				var = "ClueStagePoisonStrychnine",
			},
			{
				editor_view_abridged = "ClueStagePoisonUnknown = true",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestSetVariableBool",
				var = "ClueStagePoisonUnknown",
			},
			{
				editor_view_abridged = "Quest TwinManors:Clues =  100% from (Clues + 1)",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestSetVariableNum",
				var = "Clues",
			},
			{
				editor_view_abridged = "Play banter(s): TwinManors_StagePotion_success",
				filter_type = "banter",
				reference_id = "TwinManors_StagePotion_success",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): TwinManors_StagePotion_failure",
				filter_type = "banter",
				reference_id = "TwinManors_StagePotion_failure",
				type = "PlayBanterEffect",
			},
		},
		map = "LaRmEyu",
		name = 'CustomInteractable#961 "Examine" (SkillCheck)',
		path = "CustomInteractable ",
		type = "CustomInteractable",
	},
	{
		BanterGroups = {
			"Banters_Local_TwinManors",
			"Banters_Civilians",
		},
		Groups = {
			"FamiliesCombat",
			"AL_LeDonnas",
			"LeDonnas",
			"LeDomasCombat",
			"CivilianFemale_1",
		},
		handle = 1880209518,
		items = {},
		map = "LaRmEyu",
		name = "UnitMarker#518 (FamiliesCombat, AL_LeDonnas, LeDonnas, LeDomasCombat, CivilianFemale_1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterGroups = {
			"Banters_Local_TwinManors",
			"Banters_Civilians",
		},
		Groups = {
			"AL_VanTassel",
			"FamiliesCombat",
			"VanTassel",
			"VanTasselCombat",
			"CivilianMale_2",
		},
		handle = 1882004898,
		items = {},
		map = "LaRmEyu",
		name = "UnitMarker#898 (AL_VanTassel, FamiliesCombat, VanTassel, VanTasselCombat, CivilianMale_2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterGroups = {
			"Banters_Local_TwinManors",
		},
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"TwinManorsNPC_DrLEnfer05_SampleRequested",
				},
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = {
			"FamilyGathering",
			"AL_Doctor",
		},
		handle = 1894404302,
		items = {
			{
				editor_view_abridged = "if MangelSamples and not Sample_TwinManors and not SamplesGiven",
				filter_type = "quest",
				reference_id = "Sanatorium",
				type = "QuestIsVariableBool",
				var = set({
	MangelSamples = true,
	Sample_TwinManors = false,
	SamplesGiven = false,
}),
			},
			{
				editor_view_abridged = "if FamiliesDefeated",
				filter_type = "quest",
				reference_id = "TwinManors",
				type = "QuestIsVariableBool",
				var = set( "FamiliesDefeated" ),
			},
			{
				editor_view_abridged = "Sample_TwinManors = true",
				filter_type = "quest",
				reference_id = "Sanatorium",
				type = "QuestSetVariableBool",
				var = "Sample_TwinManors",
			},
			{
				editor_view_abridged = "Quest Sanatorium:Samples =  100% from (Samples + 1)",
				filter_type = "quest",
				reference_id = "Sanatorium",
				type = "QuestSetVariableNum",
				var = "Samples",
			},
			{
				editor_view_abridged = "Play banter(s): TwinManorsNPC_DrLEnfer05_SampleRequested",
				filter_type = "banter",
				reference_id = "TwinManorsNPC_DrLEnfer05_SampleRequested",
				type = "PlayBanterEffect",
			},
		},
		map = "LaRmEyu",
		name = "UnitMarker#302 DrLEnfer (FamilyGathering, AL_Doctor)",
		path = "UnitMarker DrLEnfer",
		type = "UnitMarker",
	},
}