{
	{
		Groups = false,
		LootTableIds = {
			"LargeContainer_Exceptional",
		},
		handle = 294232064,
		map = "DCfEzL",
		name = 'InventoryItemSpawn#064 "CONTAINER"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"LargeContainer",
		},
		handle = 299401216,
		map = "DCfEzL",
		name = 'InventoryItemSpawn#216 "CHEST"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"SmallContainer",
		},
		handle = 482770944,
		map = "DCfEzL",
		name = 'InventoryItemSpawn#944 "DEAD BODY"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"LargeContainer",
		},
		handle = 506019840,
		map = "DCfEzL",
		name = 'InventoryItemSpawn#840 "PILE"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"LargeContainer",
		},
		handle = 591421440,
		map = "DCfEzL",
		name = 'InventoryItemSpawn#440 "CONTAINER"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = {
			"AA12_Loot",
		},
		LootTableIds = {
			"FreeloaderCavern_AA12",
		},
		handle = 701521920,
		map = "DCfEzL",
		name = 'InventoryItemSpawn#920 "Weapon" (AA12_Loot)',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"LargeContainer",
		},
		handle = 863928320,
		map = "DCfEzL",
		name = 'InventoryItemSpawn#320 "PILE"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		handle = 1001500898,
		items = {},
		map = "DCfEzL",
		name = "UnitMarker#898",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1054686634,
		items = {},
		map = "DCfEzL",
		name = "UnitMarker#634",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1085821091,
		items = {},
		map = "DCfEzL",
		name = "UnitMarker#091",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1104813976,
		items = {},
		map = "DCfEzL",
		name = "UnitMarker#976",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1109703711,
		items = {},
		map = "DCfEzL",
		name = "UnitMarker#711",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1125993857,
		items = {},
		map = "DCfEzL",
		name = "UnitMarker#857",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PerimeterPatrollers",
		},
		handle = 1204287793,
		items = {},
		map = "DCfEzL",
		name = "UnitMarker#793 (PerimeterPatrollers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1215259305,
		items = {},
		map = "DCfEzL",
		name = "UnitMarker#305",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"CliffPatroller",
		},
		handle = 1257330425,
		items = {},
		map = "DCfEzL",
		name = "UnitMarker#425 (CliffPatroller)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1268768012,
		items = {},
		map = "DCfEzL",
		name = "UnitMarker#012",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PerimeterPatrollers",
		},
		handle = 1296787993,
		items = {},
		map = "DCfEzL",
		name = "UnitMarker#993 (PerimeterPatrollers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1351454239,
		items = {},
		map = "DCfEzL",
		name = "UnitMarker#239",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1353510156,
		items = {},
		map = "DCfEzL",
		name = "UnitMarker#156",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PerimeterPatrollers",
		},
		handle = 1370894663,
		items = {},
		map = "DCfEzL",
		name = "UnitMarker#663 (PerimeterPatrollers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1413302985,
		items = {},
		map = "DCfEzL",
		name = "UnitMarker#985",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1435374195,
		items = {},
		map = "DCfEzL",
		name = "UnitMarker#195",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1513077364,
		items = {},
		map = "DCfEzL",
		name = "UnitMarker#364",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1540839599,
		items = {},
		map = "DCfEzL",
		name = "UnitMarker#599",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"CliffPatroller",
		},
		handle = 1555420355,
		items = {},
		map = "DCfEzL",
		name = "UnitMarker#355 (CliffPatroller)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1582985911,
		items = {},
		map = "DCfEzL",
		name = "UnitMarker#911",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PerimeterPatrollers",
		},
		handle = 1592504217,
		items = {},
		map = "DCfEzL",
		name = "UnitMarker#217 (PerimeterPatrollers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1602256982,
		items = {},
		map = "DCfEzL",
		name = "UnitMarker#982",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1632076150,
		items = {},
		map = "DCfEzL",
		name = "UnitMarker#150",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1639123916,
		items = {},
		map = "DCfEzL",
		name = "UnitMarker#916",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1643706648,
		items = {},
		map = "DCfEzL",
		name = "UnitMarker#648",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1645083996,
		items = {},
		map = "DCfEzL",
		name = "UnitMarker#996",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1739958661,
		items = {},
		map = "DCfEzL",
		name = "UnitMarker#661",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1842133198,
		items = {},
		map = "DCfEzL",
		name = "UnitMarker#198",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1861524824,
		items = {},
		map = "DCfEzL",
		name = "UnitMarker#824",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1889252198,
		items = {},
		map = "DCfEzL",
		name = "UnitMarker#198",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
}