{
	{
		Groups = false,
		LootTableIds = {
			"SmallContainer",
		},
		handle = 429252608,
		map = "YfSFEFP",
		name = 'InventoryItemSpawn#608 "PILE"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"LargeContainer",
		},
		handle = 720437248,
		map = "YfSFEFP",
		name = 'InventoryItemSpawn#248 "CONTAINER"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		SpecificBanters = {
			"MiddleOfXWhere_Legion",
		},
		handle = 1027366620,
		map = "YfSFEFP",
		name = "Position#620",
		path = "Position ",
		type = "Position",
	},
	{
		Groups = {
			"Legion_TreasureHunters",
		},
		handle = 1039375693,
		items = {},
		map = "YfSFEFP",
		name = "UnitMarker#693 (Legion_TreasureHunters)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Legion_TreasureHunters",
		},
		handle = 1073407050,
		items = {},
		map = "YfSFEFP",
		name = "UnitMarker#050 (Legion_TreasureHunters)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Legion_TreasureHunters",
		},
		handle = 1194446604,
		items = {},
		map = "YfSFEFP",
		name = "UnitMarker#604 (Legion_TreasureHunters)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Legion_TreasureHunters",
		},
		handle = 1204197144,
		items = {},
		map = "YfSFEFP",
		name = "UnitMarker#144 (Legion_TreasureHunters)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Legion_TreasureHunters",
		},
		handle = 1258787801,
		items = {},
		map = "YfSFEFP",
		name = "UnitMarker#801 (Legion_TreasureHunters)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Legion_TreasureHunters",
		},
		handle = 1337390323,
		items = {},
		map = "YfSFEFP",
		name = "UnitMarker#323 (Legion_TreasureHunters)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Legion_TreasureHunters",
		},
		handle = 1384603592,
		items = {},
		map = "YfSFEFP",
		name = "UnitMarker#592 (Legion_TreasureHunters)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Legion_TreasureHunters",
		},
		handle = 1388548279,
		items = {},
		map = "YfSFEFP",
		name = "UnitMarker#279 (Legion_TreasureHunters)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterGroups = {
			"Banters_Local_MiddleOfWhere",
		},
		Groups = false,
		handle = 1401615568,
		items = {},
		map = "YfSFEFP",
		name = "UnitMarker#568",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Legion_TreasureHunters",
		},
		handle = 1555773953,
		items = {},
		map = "YfSFEFP",
		name = "UnitMarker#953 (Legion_TreasureHunters)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Legion_TreasureHunters",
		},
		handle = 1574828366,
		items = {},
		map = "YfSFEFP",
		name = "UnitMarker#366 (Legion_TreasureHunters)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Legion_TreasureHunters",
		},
		handle = 1587106664,
		items = {},
		map = "YfSFEFP",
		name = "UnitMarker#664 (Legion_TreasureHunters)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Legion_TreasureHunters",
		},
		handle = 1637053244,
		items = {},
		map = "YfSFEFP",
		name = "UnitMarker#244 (Legion_TreasureHunters)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Legion_TreasureHunters",
		},
		handle = 1643730809,
		items = {},
		map = "YfSFEFP",
		name = "UnitMarker#809 (Legion_TreasureHunters)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Legion_TreasureHunters",
		},
		handle = 1659812025,
		items = {},
		map = "YfSFEFP",
		name = "UnitMarker#025 (Legion_TreasureHunters)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Legion_TreasureHunters",
		},
		handle = 1727430843,
		items = {},
		map = "YfSFEFP",
		name = "UnitMarker#843 (Legion_TreasureHunters)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Legion_TreasureHunters",
		},
		handle = 1782382871,
		items = {},
		map = "YfSFEFP",
		name = "UnitMarker#871 (Legion_TreasureHunters)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
}