{
	{
		Groups = false,
		LootTableIds = {
			"LargeContainer_Exceptional",
		},
		handle = 28622848,
		map = "foGJVnR",
		name = 'InventoryItemSpawn#848 "CHEST"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"LargeContainer",
		},
		handle = 37896192,
		map = "foGJVnR",
		name = 'InventoryItemSpawn#192 "CONTAINER"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"SmallContainer",
		},
		handle = 51863552,
		map = "foGJVnR",
		name = 'InventoryItemSpawn#552 "PILE"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"LargeContainer",
		},
		handle = 677765120,
		map = "foGJVnR",
		name = 'InventoryItemSpawn#120 "CONTAINER"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"Reaction_Tex_Movie_Rambo",
				},
				banterSequentialWaitFor = "BanterStart",
			}),
		},
		Groups = {
			"TexMoviePoster_Rambo",
		},
		handle = 1058448370,
		items = {
			{
				editor_view_abridged = "Play banter(s): Reaction_Tex_Movie_Rambo",
				filter_type = "banter",
				reference_id = "Reaction_Tex_Movie_Rambo",
				type = "PlayBanterEffect",
			},
		},
		map = "foGJVnR",
		name = "Logic#370 (TexMoviePoster_Rambo)",
		path = "Logic ",
		type = "Logic",
	},
	{
		Groups = {
			"PrisonerLogic",
			"AL_Prisoners",
		},
		handle = 1067678043,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#043 (PrisonerLogic, AL_Prisoners)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PrisonerLogic",
			"AL_Prisoners",
		},
		handle = 1072355366,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#366 (PrisonerLogic, AL_Prisoners)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PrisonerLogic",
			"AL_Prisoners",
		},
		handle = 1084909574,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#574 (PrisonerLogic, AL_Prisoners)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Guards",
			"CellsPatroller",
		},
		handle = 1087365831,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#831 (Guards, CellsPatroller)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Guards",
		},
		handle = 1098168229,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#229 (Guards)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PrisonerLogic",
			"AL_Prisoners",
		},
		handle = 1146561407,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#407 (PrisonerLogic, AL_Prisoners)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PrisonerLogic",
			"AL_Prisoners",
		},
		handle = 1179877168,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#168 (PrisonerLogic, AL_Prisoners)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PrisonerLogic",
			"AL_Prisoners",
		},
		handle = 1197969417,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#417 (PrisonerLogic, AL_Prisoners)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Guards",
		},
		handle = 1212537350,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#350 (Guards)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PrisonerLogic",
			"AL_Prisoners",
		},
		handle = 1215687897,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#897 (PrisonerLogic, AL_Prisoners)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PrisonerLogic",
			"AL_Prisoners",
		},
		handle = 1218278509,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#509 (PrisonerLogic, AL_Prisoners)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PrisonerLogic",
			"AL_Prisoners",
		},
		handle = 1280972161,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#161 (PrisonerLogic, AL_Prisoners)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Guards",
			"CentralPatroller",
		},
		handle = 1305379591,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#591 (Guards, CentralPatroller)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Guards",
		},
		handle = 1341367755,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#755 (Guards)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Guards",
		},
		handle = 1368218495,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#495 (Guards)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Guards",
		},
		handle = 1370722082,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#082 (Guards)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Guards",
		},
		handle = 1387583782,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#782 (Guards)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PrisonerLogic",
			"AL_Prisoners",
		},
		handle = 1393862013,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#013 (PrisonerLogic, AL_Prisoners)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PrisonerLogic",
			"AL_Prisoners",
		},
		handle = 1402523783,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#783 (PrisonerLogic, AL_Prisoners)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Guards",
			"CentralPatroller",
		},
		handle = 1427747895,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#895 (Guards, CentralPatroller)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Guards",
		},
		handle = 1453593789,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#789 (Guards)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		ApproachedBanters = {
			"Prison_Luigi01_Approach_Initial",
			"Prison_Luigi02_Approach_Unlocked",
		},
		Groups = {
			"LuigiAndJoseph",
			"AL_Prisoners",
		},
		handle = 1464631894,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#894 (LuigiAndJoseph, AL_Prisoners)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PrisonerLogic",
			"AL_Prisoners",
		},
		handle = 1506584766,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#766 (PrisonerLogic, AL_Prisoners)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PrisonerLogic",
			"AL_Prisoners",
		},
		handle = 1615272916,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#916 (PrisonerLogic, AL_Prisoners)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		ApproachedBanters = {
			"ElliotApproach_01",
		},
		BanterGroups = {
			"Banters_Local_GoodPlace",
		},
		Groups = {
			"AL_Prisoners",
		},
		handle = 1656086412,
		items = {
			{
				editor_view_abridged = "if ElliotExposed and ElliotInPrison and ElliotLeave",
				filter_type = "quest",
				reference_id = "Elliot",
				type = "QuestIsVariableBool",
				var = set( "ElliotExposed", "ElliotInPrison", "ElliotLeave" ),
			},
		},
		map = "foGJVnR",
		name = "UnitMarker#412 (AL_Prisoners)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterGroups = {
			"Banters_Local_GoodPlace",
		},
		Groups = {
			"AL_Prisoners",
		},
		handle = 1664247113,
		items = {
			{
				editor_view_abridged = "if not JackhammerDead and JackhammerPrisoner and not JackhammerRelease",
				filter_type = "quest",
				reference_id = "Luigi",
				type = "QuestIsVariableBool",
				var = set({
	JackhammerDead = false,
	JackhammerPrisoner = true,
	JackhammerRelease = false,
}),
			},
		},
		map = "foGJVnR",
		name = "UnitMarker#113 (AL_Prisoners)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PrisonerLogic",
			"AL_Prisoners",
		},
		handle = 1691736063,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#063 (PrisonerLogic, AL_Prisoners)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Guards",
			"CorridorPatroller",
		},
		handle = 1725340395,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#395 (Guards, CorridorPatroller)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Guards",
			"CorridorPatroller",
		},
		handle = 1747405924,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#924 (Guards, CorridorPatroller)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Guards",
		},
		handle = 1753959347,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#347 (Guards)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LuigiAndJoseph",
			"AL_Prisoners",
		},
		handle = 1785942550,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#550 (LuigiAndJoseph, AL_Prisoners)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Guards",
		},
		handle = 1791898933,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#933 (Guards)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Guards",
		},
		handle = 1833647025,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#025 (Guards)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Guards",
		},
		handle = 1837856247,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#247 (Guards)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Guards",
			"CellsPatroller",
		},
		handle = 1843059270,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#270 (Guards, CellsPatroller)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PrisonerLogic",
			"AL_Prisoners",
		},
		handle = 1848351238,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#238 (PrisonerLogic, AL_Prisoners)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PrisonerLogic",
			"AL_Prisoners",
		},
		handle = 1856058329,
		items = {},
		map = "foGJVnR",
		name = "UnitMarker#329 (PrisonerLogic, AL_Prisoners)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
}