{
	{
		Groups = false,
		LootTableIds = {
			"IntelSecretStash",
		},
		handle = 83804160,
		map = "LmmShMY",
		name = 'IntelInventoryItemSpawn#160 "SECRET STASH"',
		path = "IntelInventoryItemSpawn ",
		type = "IntelInventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"SmallContainer_BushesTreasure",
		},
		handle = 506691584,
		items = {
			{
				editor_view_abridged = "if BushesTreasure_F9 == 1 ",
				filter_type = "quest",
				reference_id = "TreasureHunting",
				type = "QuestIsVariableNum",
				var = "BushesTreasure_F9",
			},
			{
				editor_view_abridged = "if BushesTreasure_F9 == 2 ",
				filter_type = "quest",
				reference_id = "TreasureHunting",
				type = "QuestIsVariableNum",
				var = "BushesTreasure_F9",
			},
		},
		map = "LmmShMY",
		name = 'InventoryItemSpawn#584 "CONTAINER"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"SmallContainer",
		},
		handle = 767336448,
		map = "LmmShMY",
		name = 'InventoryItemSpawn#448 "Bag"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"LargeContainer_Exceptional",
		},
		handle = 770334720,
		items = {
			{
				editor_view_abridged = "if BusGang_wait2completed",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableBool",
				var = set( "BusGang_wait2completed" ),
			},
			{
				editor_view_abridged = "if BusRandom == 1 ",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableNum",
				var = "BusRandom",
			},
			{
				editor_view_abridged = "if BusGangDefeated",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableBool",
				var = set( "BusGangDefeated" ),
			},
		},
		map = "LmmShMY",
		name = 'InventoryItemSpawn#720 "Bus"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"LargeContainer_Exceptional",
		},
		handle = 966656000,
		items = {
			{
				editor_view_abridged = "if BusGang_wait2completed",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableBool",
				var = set( "BusGang_wait2completed" ),
			},
			{
				editor_view_abridged = "if BusRandom == 2 ",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableNum",
				var = "BusRandom",
			},
			{
				editor_view_abridged = "if TCE_BusGang_Defeated",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableBool",
				var = set( "TCE_BusGang_Defeated" ),
			},
		},
		map = "LmmShMY",
		name = 'InventoryItemSpawn#000 "Bus"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = {
			"BusGang",
		},
		handle = 1038033671,
		items = {
			{
				editor_view_abridged = "if BusGang_wait2completed",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableBool",
				var = set( "BusGang_wait2completed" ),
			},
			{
				editor_view_abridged = "if BusRandom == 2 ",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableNum",
				var = "BusRandom",
			},
		},
		map = "LmmShMY",
		name = "UnitMarker#671 (BusGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"BusGang",
		},
		handle = 1065802061,
		items = {
			{
				editor_view_abridged = "if BusGang_wait2completed",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableBool",
				var = set( "BusGang_wait2completed" ),
			},
			{
				editor_view_abridged = "if BusRandom == 1 ",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableNum",
				var = "BusRandom",
			},
		},
		map = "LmmShMY",
		name = "UnitMarker#061 (BusGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"BusGang",
		},
		handle = 1093290237,
		items = {
			{
				editor_view_abridged = "if BusGang_wait2completed",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableBool",
				var = set( "BusGang_wait2completed" ),
			},
			{
				editor_view_abridged = "if BusRandom == 2 ",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableNum",
				var = "BusRandom",
			},
		},
		map = "LmmShMY",
		name = "UnitMarker#237 (BusGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1137822741,
		items = {
			{
				editor_view_abridged = "if BusGang_wait2completed",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableBool",
				var = set( "BusGang_wait2completed" ),
			},
			{
				editor_view_abridged = "if BusRandom == 2 ",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableNum",
				var = "BusRandom",
			},
		},
		map = "LmmShMY",
		name = "Position#741",
		path = "Position ",
		type = "Position",
	},
	{
		Groups = {
			"BusGang",
		},
		handle = 1162817766,
		items = {
			{
				editor_view_abridged = "if BusGang_wait2completed",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableBool",
				var = set( "BusGang_wait2completed" ),
			},
			{
				editor_view_abridged = "if BusRandom == 1 ",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableNum",
				var = "BusRandom",
			},
		},
		map = "LmmShMY",
		name = "UnitMarker#766 (BusGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"BusGang",
		},
		handle = 1182729933,
		items = {
			{
				editor_view_abridged = "if BusGang_wait2completed",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableBool",
				var = set( "BusGang_wait2completed" ),
			},
			{
				editor_view_abridged = "if BusRandom == 2 ",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableNum",
				var = "BusRandom",
			},
		},
		map = "LmmShMY",
		name = "UnitMarker#933 (BusGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"BusGang",
		},
		handle = 1203526071,
		items = {
			{
				editor_view_abridged = "if BusGang_wait2completed",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableBool",
				var = set( "BusGang_wait2completed" ),
			},
			{
				editor_view_abridged = "if BusRandom == 1 ",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableNum",
				var = "BusRandom",
			},
		},
		map = "LmmShMY",
		name = "UnitMarker#071 (BusGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1218165087,
		items = {
			{
				editor_view_abridged = "if BusGang_wait2completed",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableBool",
				var = set( "BusGang_wait2completed" ),
			},
			{
				editor_view_abridged = "if BusRandom == 2 ",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableNum",
				var = "BusRandom",
			},
		},
		map = "LmmShMY",
		name = "Position#087",
		path = "Position ",
		type = "Position",
	},
	{
		Groups = false,
		handle = 1243854011,
		items = {
			{
				editor_view_abridged = "if BusGang_wait2completed",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableBool",
				var = set( "BusGang_wait2completed" ),
			},
			{
				editor_view_abridged = "if BusRandom == 2 ",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableNum",
				var = "BusRandom",
			},
		},
		map = "LmmShMY",
		name = "Position#011",
		path = "Position ",
		type = "Position",
	},
	{
		Groups = {
			"BusGang",
		},
		handle = 1308490611,
		items = {
			{
				editor_view_abridged = "if BusGang_wait2completed",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableBool",
				var = set( "BusGang_wait2completed" ),
			},
			{
				editor_view_abridged = "if BusRandom == 2 ",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableNum",
				var = "BusRandom",
			},
		},
		map = "LmmShMY",
		name = "UnitMarker#611 (BusGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"BusGang",
		},
		handle = 1377842631,
		items = {
			{
				editor_view_abridged = "if BusGang_wait2completed",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableBool",
				var = set( "BusGang_wait2completed" ),
			},
			{
				editor_view_abridged = "if BusRandom == 1 ",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableNum",
				var = "BusRandom",
			},
		},
		map = "LmmShMY",
		name = "UnitMarker#631 (BusGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"Bushes_MacheteCut",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"Bushes_NoMachete",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = {
			"ThornyBushes",
		},
		handle = 1398922258,
		items = {
			{
				editor_view_abridged = "if BushesTreasure_F9 == 1 ",
				filter_type = "quest",
				reference_id = "TreasureHunting",
				type = "QuestIsVariableNum",
				var = "BushesTreasure_F9",
			},
			{
				editor_view_abridged = "Quest TreasureHunting:BushesTreasure_F9 = 2",
				filter_type = "quest",
				reference_id = "TreasureHunting",
				type = "QuestSetVariableNum",
				var = "BushesTreasure_F9",
			},
			{
				editor_view_abridged = "Play banter(s): Bushes_MacheteCut",
				filter_type = "banter",
				reference_id = "Bushes_MacheteCut",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): Bushes_NoMachete",
				filter_type = "banter",
				reference_id = "Bushes_NoMachete",
				type = "PlayBanterEffect",
			},
		},
		map = "LmmShMY",
		name = 'CustomInteractable#258 "Cut Bushes" (ThornyBushes)',
		path = "CustomInteractable ",
		type = "CustomInteractable",
	},
	{
		Groups = {
			"BusGang",
		},
		handle = 1415814980,
		items = {
			{
				editor_view_abridged = "if BusGang_wait2completed",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableBool",
				var = set( "BusGang_wait2completed" ),
			},
			{
				editor_view_abridged = "if BusRandom == 1 ",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableNum",
				var = "BusRandom",
			},
		},
		map = "LmmShMY",
		name = "UnitMarker#980 (BusGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1460176430,
		items = {
			{
				editor_view_abridged = "if BusGang_wait2completed",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableBool",
				var = set( "BusGang_wait2completed" ),
			},
			{
				editor_view_abridged = "if BusRandom == 1 ",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableNum",
				var = "BusRandom",
			},
		},
		map = "LmmShMY",
		name = "Position#430",
		path = "Position ",
		type = "Position",
	},
	{
		Groups = {
			"BusGang",
		},
		handle = 1486976360,
		items = {
			{
				editor_view_abridged = "if BusGang_wait2completed",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableBool",
				var = set( "BusGang_wait2completed" ),
			},
			{
				editor_view_abridged = "if BusRandom == 2 ",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableNum",
				var = "BusRandom",
			},
		},
		map = "LmmShMY",
		name = "UnitMarker#360 (BusGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"BusGang",
		},
		handle = 1488163852,
		items = {
			{
				editor_view_abridged = "if BusGang_wait2completed",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableBool",
				var = set( "BusGang_wait2completed" ),
			},
			{
				editor_view_abridged = "if BusRandom == 2 ",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableNum",
				var = "BusRandom",
			},
		},
		map = "LmmShMY",
		name = "UnitMarker#852 (BusGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"BusGang",
		},
		handle = 1493365972,
		items = {
			{
				editor_view_abridged = "if BusGang_wait2completed",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableBool",
				var = set( "BusGang_wait2completed" ),
			},
			{
				editor_view_abridged = "if BusRandom == 1 ",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableNum",
				var = "BusRandom",
			},
		},
		map = "LmmShMY",
		name = "UnitMarker#972 (BusGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1533821685,
		items = {
			{
				editor_view_abridged = "if BusGang_wait2completed",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableBool",
				var = set( "BusGang_wait2completed" ),
			},
			{
				editor_view_abridged = "if BusRandom == 1 ",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableNum",
				var = "BusRandom",
			},
		},
		map = "LmmShMY",
		name = "Position#685",
		path = "Position ",
		type = "Position",
	},
	{
		Groups = {
			"BusGang",
		},
		handle = 1625835114,
		items = {
			{
				editor_view_abridged = "if BusGang_wait2completed",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableBool",
				var = set( "BusGang_wait2completed" ),
			},
			{
				editor_view_abridged = "if BusRandom == 2 ",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableNum",
				var = "BusRandom",
			},
		},
		map = "LmmShMY",
		name = "UnitMarker#114 (BusGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"BusGang",
		},
		handle = 1651682636,
		items = {
			{
				editor_view_abridged = "if BusGang_wait2completed",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableBool",
				var = set( "BusGang_wait2completed" ),
			},
			{
				editor_view_abridged = "if BusRandom == 1 ",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableNum",
				var = "BusRandom",
			},
		},
		map = "LmmShMY",
		name = "UnitMarker#636 (BusGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"Jungle_BusGang_initial",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = false,
		handle = 1698215228,
		items = {
			{
				editor_view_abridged = "Play banter(s): Jungle_BusGang_initial",
				filter_type = "banter",
				reference_id = "Jungle_BusGang_initial",
				type = "PlayBanterEffect",
			},
		},
		map = "LmmShMY",
		name = 'CustomInteractable#228 "Examine"',
		path = "CustomInteractable ",
		type = "CustomInteractable",
	},
	{
		Groups = false,
		handle = 1755727445,
		items = {
			{
				editor_view_abridged = "if BusGang_wait2completed",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableBool",
				var = set( "BusGang_wait2completed" ),
			},
			{
				editor_view_abridged = "if BusRandom == 1 ",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableNum",
				var = "BusRandom",
			},
		},
		map = "LmmShMY",
		name = "Position#445",
		path = "Position ",
		type = "Position",
	},
	{
		Groups = false,
		handle = 1769924504,
		items = {
			{
				editor_view_abridged = "if BushesTreasure_F9 == 2 ",
				filter_type = "quest",
				reference_id = "TreasureHunting",
				type = "QuestIsVariableNum",
				var = "BushesTreasure_F9",
			},
		},
		map = "LmmShMY",
		name = "Position#504",
		path = "Position ",
		type = "Position",
	},
	{
		Groups = false,
		handle = 1775117684,
		items = {
			{
				editor_view_abridged = "if BusGang_wait2completed",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableBool",
				var = set( "BusGang_wait2completed" ),
			},
			{
				editor_view_abridged = "if BusRandom == 2 ",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableNum",
				var = "BusRandom",
			},
		},
		map = "LmmShMY",
		name = "Position#684",
		path = "Position ",
		type = "Position",
	},
	{
		Groups = {
			"BusGang",
		},
		handle = 1849395480,
		items = {
			{
				editor_view_abridged = "if BusGang_wait2completed",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableBool",
				var = set( "BusGang_wait2completed" ),
			},
			{
				editor_view_abridged = "if BusRandom == 1 ",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableNum",
				var = "BusRandom",
			},
		},
		map = "LmmShMY",
		name = "UnitMarker#480 (BusGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"BusGang",
		},
		handle = 1893533742,
		items = {
			{
				editor_view_abridged = "if BusGang_wait2completed",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableBool",
				var = set( "BusGang_wait2completed" ),
			},
			{
				editor_view_abridged = "if BusRandom == 2 ",
				filter_type = "quest",
				reference_id = "FleatownGeneral",
				type = "QuestIsVariableNum",
				var = "BusRandom",
			},
		},
		map = "LmmShMY",
		name = "UnitMarker#742 (BusGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
}